name=ESP32-HTTP-Client
version=1.2.1
author=Pedro Fonseca
maintainer=Pedro Fonseca <pedro@email.com>
sentence=Lightweight HTTP client for ESP32 with direct JSON stream parsing into variables.
paragraph=No JSON decoding. No String objects. No boilerplate. Parses JSON streams directly into variables.
category=Communication
url=https://github.com/PedroFnseca/esp32-http-client
architectures=esp32
includes=ESP32HTTPClient.h
