name=ESP32HTTPClient
version=1.0.0
author=PedroFnseca
maintainer=Pedro Fonseca
sentence=LProvides a lightweight abstraction layer for HTTP requests on ESP32, allowing direct JSON stream parsing into variables without dynamic String allocation.
paragraph=No JSON decoding. No String objects. No boilerplate. Parses JSON streams directly into variables.
category=Communication
url=https://github.com/PedroFnseca/esp32-http-client
architectures=esp32
includes=ESP32HTTPClient.h
