name=ESP32-HTTP-Client
version=1.0.0
author=PedroFnseca
maintainer=PedroFnseca
sentence=Lightweight, object-oriented REST and HTTP Client for ESP32.
paragraph=No JSON decoding. No String objects. No boilerplate. Parses JSON streams directly into variables.
category=Communication
url=https://github.com/PedroFnseca/esp32-http-client
architectures=esp32
includes=ESP32HTTPClient.h
